tables:

  subcategories:
    URL: https://jsonocean.com/api/khaled-gohar/4tfhykpm

  shipments:
    URL: https://jsonocean.com/api/khaled-gohar/u19f4nj4

  cities:
    URL: https://jsonocean.com/api/khaled-gohar/4wkenxl2
